name: chapturn_browser_extension
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.15.0 <3.0.0"

# To upgrade: `flutter pub upgrade --major-versions`
# To check: `flutter pub outdated`
dependencies:
    flutter:
        sdk: flutter
    chapturn_sources:
        path: ../chapturn_sources
    epublib:
        path: ../epublib

    provider: ^6.0.1
    http: ^0.13.4
    path: ^1.8.0
    tuple: ^2.0.0
    equatable: ^2.0.3
    injectable: ^1.5.0
    get_it: ^7.2.0
    js: ^0.6.3
    font_awesome_flutter: ^9.2.0
    url_launcher: ^6.0.17

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0
    injectable_generator: ^1.5.2
    build_runner: ^2.1.7

# https://dart.dev/tools/pub/pubspec
flutter:
    uses-material-design: true

    assets:
        - assets/images/abstract.jpg
        - assets/images/book-thumbnail.png
